name: Minify All JavaScript and CSS Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install necessary minification tools
      - name: Install Minification Tools
        run: |
          npm install -g uglify-js csso-cli

      # Minify all JavaScript files in the repository and create .min.js files
      - name: Minify JavaScript files
        run: |
          find . -name '*.js' -not -name '*.min.js' | while read jsfile; do
            minfile="${jsfile%.js}.min.js"
            uglifyjs "$jsfile" --compress --mangle -o "$minfile"
          done

      # Minify all CSS files in the repository and create .min.css files
      - name: Minify CSS files
        run: |
          find . -name '*.css' -not -name '*.min.css' | while read cssfile; do
            minfile="${cssfile%.css}.min.css"
            csso "$cssfile" --output "$minfile"
          done

      # Commit the changes if there are any
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Minified JS and CSS files"
          git push
        if: success()
